#!/bin/bash
echo "🚀 Quick Deploy Script"
echo ""
echo "Step 1: Create GitHub repo"
echo "  - Go to github.com/new"
echo "  - Name it: orbital-debris-visualizer"
echo "  - Don't initialize with README"
echo ""
echo "Step 2: Run these commands:"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git branch -M main"
echo "git remote add origin https://github.com/YOUR_USERNAME/orbital-debris-visualizer.git"
echo "git push -u origin main"
echo ""
echo "Step 3: Deploy on Render"
echo "  - Go to render.com"
echo "  - New Web Service"
echo "  - Connect GitHub repo"
echo "  - Add env vars (see DEPLOY.md)"
echo "  - Deploy!"
echo ""
echo "Done! 🎉"
